import {
  Baby,
  BadgePercent,
  Banknote,
  Beer,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Bus,
  CakeSlice,
  Camera,
  Car,
  CarFront,
  Cat,
  CircleDollarSign,
  Clapperboard,
  Coffee,
  Coins,
  CreditCard,
  Croissant,
  Dog,
  Droplets,
  Drumstick,
  Dumbbell,
  Flower2,
  Fuel,
  Gamepad2,
  Gift,
  GlassWater,
  GraduationCap,
  HandCoins,
  Heart,
  HeartPulse,
  Home,
  Lamp,
  Laptop,
  Leaf,
  Music,
  PartyPopper,
  PawPrint,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  Popcorn,
  Receipt,
  ReceiptText,
  Scissors,
  Shirt,
  Ship,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Sofa,
  Sparkles,
  Stethoscope,
  Store,
  Sun,
  TramFront,
  TrainFront,
  TreePine,
  TrendingUp,
  Trophy,
  Tv,
  User,
  Users,
  Utensils,
  UtensilsCrossed,
  Wallet,
  WashingMachine,
  Wifi,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react"

export const CATEGORY_ICONS = {
  // Food & drink
  utensils: Utensils,
  "utensils-crossed": UtensilsCrossed,
  pizza: Pizza,
  drumstick: Drumstick,
  croissant: Croissant,
  "cake-slice": CakeSlice,
  coffee: Coffee,
  beer: Beer,
  wine: Wine,
  "glass-water": GlassWater,
  // Shopping
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  "shopping-basket": ShoppingBasket,
  store: Store,
  gift: Gift,
  shirt: Shirt,
  scissors: Scissors,
  // Transport
  car: Car,
  "car-front": CarFront,
  bus: Bus,
  "train-front": TrainFront,
  "tram-front": TramFront,
  bike: Bike,
  plane: Plane,
  ship: Ship,
  fuel: Fuel,
  // Home & utilities
  home: Home,
  sofa: Sofa,
  tv: Tv,
  "washing-machine": WashingMachine,
  zap: Zap,
  wifi: Wifi,
  plug: Plug,
  droplets: Droplets,
  lamp: Lamp,
  wrench: Wrench,
  // Health & fitness
  heart: Heart,
  "heart-pulse": HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  dumbbell: Dumbbell,
  brain: Brain,
  // Family & pets
  baby: Baby,
  dog: Dog,
  cat: Cat,
  "paw-print": PawPrint,
  user: User,
  users: Users,
  // Work & learning
  briefcase: Briefcase,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  laptop: Laptop,
  // Money
  wallet: Wallet,
  banknote: Banknote,
  "credit-card": CreditCard,
  coins: Coins,
  "piggy-bank": PiggyBank,
  receipt: Receipt,
  "receipt-text": ReceiptText,
  "circle-dollar-sign": CircleDollarSign,
  "hand-coins": HandCoins,
  "trending-up": TrendingUp,
  "badge-percent": BadgePercent,
  // Fun & leisure
  "gamepad-2": Gamepad2,
  clapperboard: Clapperboard,
  music: Music,
  camera: Camera,
  popcorn: Popcorn,
  trophy: Trophy,
  "party-popper": PartyPopper,
  // Nature & other
  leaf: Leaf,
  "tree-pine": TreePine,
  "flower-2": Flower2,
  sun: Sun,
  sparkles: Sparkles,
} satisfies Record<string, LucideIcon>

export type CategoryIconName = keyof typeof CATEGORY_ICONS

export const CATEGORY_ICON_NAMES = Object.keys(
  CATEGORY_ICONS,
) as CategoryIconName[]
