// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auths.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuth = `-- name: CreateAuth :one
INSERT INTO auths (
    user_id,
    provider,
    provider_account_id
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, user_id, provider, provider_account_id, created_at, updated_at
`

type CreateAuthParams struct {
	UserID            pgtype.UUID
	Provider          NullLoginProvider
	ProviderAccountID string
}

func (q *Queries) CreateAuth(ctx context.Context, arg CreateAuthParams) (Auth, error) {
	row := q.db.QueryRow(ctx, createAuth, arg.UserID, arg.Provider, arg.ProviderAccountID)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAuth = `-- name: DeleteAuth :exec
DELETE FROM auths WHERE id = $1
`

func (q *Queries) DeleteAuth(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuth, id)
	return err
}

const deleteAuthByUserAndProvider = `-- name: DeleteAuthByUserAndProvider :exec
DELETE FROM auths WHERE user_id = $1 AND provider = $2
`

type DeleteAuthByUserAndProviderParams struct {
	UserID   pgtype.UUID
	Provider NullLoginProvider
}

func (q *Queries) DeleteAuthByUserAndProvider(ctx context.Context, arg DeleteAuthByUserAndProviderParams) error {
	_, err := q.db.Exec(ctx, deleteAuthByUserAndProvider, arg.UserID, arg.Provider)
	return err
}

const deleteAuthsByUserID = `-- name: DeleteAuthsByUserID :exec
DELETE FROM auths WHERE user_id = $1
`

func (q *Queries) DeleteAuthsByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthsByUserID, userID)
	return err
}

const getAuthByID = `-- name: GetAuthByID :one
SELECT id, user_id, provider, provider_account_id, created_at, updated_at FROM auths WHERE id = $1
`

func (q *Queries) GetAuthByID(ctx context.Context, id pgtype.UUID) (Auth, error) {
	row := q.db.QueryRow(ctx, getAuthByID, id)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthByProviderAccountID = `-- name: GetAuthByProviderAccountID :one
SELECT id, user_id, provider, provider_account_id, created_at, updated_at FROM auths WHERE provider = $1 AND provider_account_id = $2
`

type GetAuthByProviderAccountIDParams struct {
	Provider          NullLoginProvider
	ProviderAccountID string
}

func (q *Queries) GetAuthByProviderAccountID(ctx context.Context, arg GetAuthByProviderAccountIDParams) (Auth, error) {
	row := q.db.QueryRow(ctx, getAuthByProviderAccountID, arg.Provider, arg.ProviderAccountID)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthByUserAndProvider = `-- name: GetAuthByUserAndProvider :one
SELECT id, user_id, provider, provider_account_id, created_at, updated_at FROM auths WHERE user_id = $1 AND provider = $2
`

type GetAuthByUserAndProviderParams struct {
	UserID   pgtype.UUID
	Provider NullLoginProvider
}

func (q *Queries) GetAuthByUserAndProvider(ctx context.Context, arg GetAuthByUserAndProviderParams) (Auth, error) {
	row := q.db.QueryRow(ctx, getAuthByUserAndProvider, arg.UserID, arg.Provider)
	var i Auth
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthsByUserID = `-- name: ListAuthsByUserID :many
SELECT id, user_id, provider, provider_account_id, created_at, updated_at FROM auths WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAuthsByUserID(ctx context.Context, userID pgtype.UUID) ([]Auth, error) {
	rows, err := q.db.Query(ctx, listAuthsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Auth
	for rows.Next() {
		var i Auth
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
