// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    group_id,
    created_by,
    name,
    icon,
    color
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, group_id, created_by, name, icon, color, created_at, updated_at
`

type CreateCategoryParams struct {
	GroupID   pgtype.UUID `json:"group_id"`
	CreatedBy pgtype.UUID `json:"created_by"`
	Name      string      `json:"name"`
	Icon      pgtype.Text `json:"icon"`
	Color     string      `json:"color"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.GroupID,
		arg.CreatedBy,
		arg.Name,
		arg.Icon,
		arg.Color,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, group_id, created_by, name, icon, color, created_at, updated_at FROM categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByNameAndGroup = `-- name: GetCategoryByNameAndGroup :one
SELECT id, group_id, created_by, name, icon, color, created_at, updated_at FROM categories WHERE name = $1 AND group_id = $2
`

type GetCategoryByNameAndGroupParams struct {
	Name    string      `json:"name"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) GetCategoryByNameAndGroup(ctx context.Context, arg GetCategoryByNameAndGroupParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByNameAndGroup, arg.Name, arg.GroupID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoriesByGroupID = `-- name: ListCategoriesByGroupID :many
SELECT id, group_id, created_by, name, icon, color, created_at, updated_at FROM categories WHERE group_id = $1 ORDER BY name ASC
LIMIT $3 OFFSET $2
`

type ListCategoriesByGroupIDParams struct {
	GroupID    pgtype.UUID `json:"group_id"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

func (q *Queries) ListCategoriesByGroupID(ctx context.Context, arg ListCategoriesByGroupIDParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByGroupID, arg.GroupID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatedBy,
			&i.Name,
			&i.Icon,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET
    name = COALESCE($1, name),
    icon = COALESCE($2, icon),
    color = COALESCE($3, color)
WHERE id = $4
RETURNING id, group_id, created_by, name, icon, color, created_at, updated_at
`

type UpdateCategoryParams struct {
	Name  pgtype.Text `json:"name"`
	Icon  pgtype.Text `json:"icon"`
	Color pgtype.Text `json:"color"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.Icon,
		arg.Color,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.Name,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
