// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateExpenseSplitsBatch implements pgx.CopyFromSource.
type iteratorForCreateExpenseSplitsBatch struct {
	rows                 []CreateExpenseSplitsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateExpenseSplitsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateExpenseSplitsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ExpenseID,
		r.rows[0].UserID,
		r.rows[0].AmountOwed,
		r.rows[0].Percentage,
		r.rows[0].Shares,
	}, nil
}

func (r iteratorForCreateExpenseSplitsBatch) Err() error {
	return nil
}

func (q *Queries) CreateExpenseSplitsBatch(ctx context.Context, arg []CreateExpenseSplitsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"expense_splits"}, []string{"expense_id", "user_id", "amount_owed", "percentage", "shares"}, &iteratorForCreateExpenseSplitsBatch{rows: arg})
}
