// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDashboardActiveGroupCount = `-- name: GetDashboardActiveGroupCount :one
SELECT COUNT(*)::bigint AS active_group_count
FROM group_members
WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) GetDashboardActiveGroupCount(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getDashboardActiveGroupCount, userID)
	var active_group_count int64
	err := row.Scan(&active_group_count)
	return active_group_count, err
}

const getDashboardBalancesSummary = `-- name: GetDashboardBalancesSummary :many
SELECT
    g.id AS group_id,
    g.name AS group_name,
    COALESCE(paid_agg.paid, 0)::decimal(14,2) AS paid,
    COALESCE(owed_agg.owed, 0)::decimal(14,2) AS owed,
    COALESCE(st_agg.settled_to, 0)::decimal(14,2) AS settled_to,
    COALESCE(sf_agg.settled_from, 0)::decimal(14,2) AS settled_from
FROM groups g
JOIN group_members gm ON gm.group_id = g.id AND gm.user_id = $1 AND gm.status = 'active'
LEFT JOIN (
    SELECT e.group_id, SUM(e.amount)::decimal(14,2) AS paid FROM expenses e
    WHERE e.paid_by = $1 AND e.is_archived = FALSE GROUP BY e.group_id
) paid_agg ON paid_agg.group_id = g.id
LEFT JOIN (
    SELECT e.group_id, SUM(es.amount_owed)::decimal(14,2) AS owed FROM expense_splits es
    JOIN expenses e ON e.id = es.expense_id
    WHERE es.user_id = $1 AND e.is_archived = FALSE GROUP BY e.group_id
) owed_agg ON owed_agg.group_id = g.id
LEFT JOIN (
    SELECT s.group_id, SUM(s.amount)::decimal(14,2) AS settled_to FROM settlements s
    WHERE s.to_user_id = $1 GROUP BY s.group_id
) st_agg ON st_agg.group_id = g.id
LEFT JOIN (
    SELECT s.group_id, SUM(s.amount)::decimal(14,2) AS settled_from FROM settlements s
    WHERE s.from_user_id = $1 GROUP BY s.group_id
) sf_agg ON sf_agg.group_id = g.id
ORDER BY g.name ASC
`

type GetDashboardBalancesSummaryRow struct {
	GroupID     pgtype.UUID    `json:"group_id"`
	GroupName   string         `json:"group_name"`
	Paid        pgtype.Numeric `json:"paid"`
	Owed        pgtype.Numeric `json:"owed"`
	SettledTo   pgtype.Numeric `json:"settled_to"`
	SettledFrom pgtype.Numeric `json:"settled_from"`
}

func (q *Queries) GetDashboardBalancesSummary(ctx context.Context, userID pgtype.UUID) ([]GetDashboardBalancesSummaryRow, error) {
	rows, err := q.db.Query(ctx, getDashboardBalancesSummary, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDashboardBalancesSummaryRow
	for rows.Next() {
		var i GetDashboardBalancesSummaryRow
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupName,
			&i.Paid,
			&i.Owed,
			&i.SettledTo,
			&i.SettledFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardByCategory = `-- name: GetDashboardByCategory :many
SELECT
    c.id AS category_id,
    c.name AS category_name,
    c.color AS category_color,
    c.icon AS category_icon,
    COUNT(DISTINCT e.id)::bigint AS expense_count,
    COALESCE(SUM(e.amount), 0)::decimal(14,2) AS total_amount
FROM expenses e
LEFT JOIN categories c ON c.id = e.category_id
JOIN group_members gm ON gm.group_id = e.group_id AND gm.user_id = $1 AND gm.status = 'active'
WHERE e.expense_date BETWEEN $2 AND $3
  AND e.is_archived = FALSE
  AND (e.paid_by = $1 OR EXISTS (SELECT 1 FROM expense_splits es2 WHERE es2.expense_id = e.id AND es2.user_id = $1))
GROUP BY c.id, c.name, c.color, c.icon
ORDER BY total_amount DESC
`

type GetDashboardByCategoryParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type GetDashboardByCategoryRow struct {
	CategoryID    pgtype.UUID    `json:"category_id"`
	CategoryName  pgtype.Text    `json:"category_name"`
	CategoryColor pgtype.Text    `json:"category_color"`
	CategoryIcon  pgtype.Text    `json:"category_icon"`
	ExpenseCount  int64          `json:"expense_count"`
	TotalAmount   pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) GetDashboardByCategory(ctx context.Context, arg GetDashboardByCategoryParams) ([]GetDashboardByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getDashboardByCategory, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDashboardByCategoryRow
	for rows.Next() {
		var i GetDashboardByCategoryRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryColor,
			&i.CategoryIcon,
			&i.ExpenseCount,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardByCurrency = `-- name: GetDashboardByCurrency :many
SELECT
    g.default_currency AS currency,
    COUNT(DISTINCT e.id)::bigint AS expense_count,
    COALESCE(SUM(e.amount), 0)::decimal(14,2) AS total_amount
FROM expenses e
JOIN groups g ON g.id = e.group_id
JOIN group_members gm ON gm.group_id = e.group_id AND gm.user_id = $1 AND gm.status = 'active'
WHERE e.expense_date BETWEEN $2 AND $3
  AND e.is_archived = FALSE
  AND (e.paid_by = $1 OR EXISTS (SELECT 1 FROM expense_splits es2 WHERE es2.expense_id = e.id AND es2.user_id = $1))
GROUP BY g.default_currency
ORDER BY total_amount DESC
`

type GetDashboardByCurrencyParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type GetDashboardByCurrencyRow struct {
	Currency     string         `json:"currency"`
	ExpenseCount int64          `json:"expense_count"`
	TotalAmount  pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) GetDashboardByCurrency(ctx context.Context, arg GetDashboardByCurrencyParams) ([]GetDashboardByCurrencyRow, error) {
	rows, err := q.db.Query(ctx, getDashboardByCurrency, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDashboardByCurrencyRow
	for rows.Next() {
		var i GetDashboardByCurrencyRow
		if err := rows.Scan(&i.Currency, &i.ExpenseCount, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardByGroup = `-- name: GetDashboardByGroup :many
SELECT
    g.id AS group_id,
    g.name AS group_name,
    g.default_currency AS group_currency,
    COUNT(DISTINCT e.id)::bigint AS expense_count,
    COALESCE(SUM(e.amount), 0)::decimal(14,2) AS total_amount
FROM expenses e
JOIN groups g ON g.id = e.group_id
JOIN group_members gm ON gm.group_id = e.group_id AND gm.user_id = $1 AND gm.status = 'active'
WHERE e.expense_date BETWEEN $2 AND $3
  AND e.is_archived = FALSE
  AND (e.paid_by = $1 OR EXISTS (SELECT 1 FROM expense_splits es2 WHERE es2.expense_id = e.id AND es2.user_id = $1))
GROUP BY g.id, g.name, g.default_currency
ORDER BY total_amount DESC
`

type GetDashboardByGroupParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type GetDashboardByGroupRow struct {
	GroupID       pgtype.UUID    `json:"group_id"`
	GroupName     string         `json:"group_name"`
	GroupCurrency string         `json:"group_currency"`
	ExpenseCount  int64          `json:"expense_count"`
	TotalAmount   pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) GetDashboardByGroup(ctx context.Context, arg GetDashboardByGroupParams) ([]GetDashboardByGroupRow, error) {
	rows, err := q.db.Query(ctx, getDashboardByGroup, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDashboardByGroupRow
	for rows.Next() {
		var i GetDashboardByGroupRow
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupName,
			&i.GroupCurrency,
			&i.ExpenseCount,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardDaily = `-- name: GetDashboardDaily :many
SELECT
    e.expense_date AS expense_date,
    COUNT(DISTINCT e.id)::bigint AS expense_count,
    COALESCE(SUM(e.amount), 0)::decimal(14,2) AS total_amount
FROM expenses e
JOIN group_members gm ON gm.group_id = e.group_id AND gm.user_id = $1 AND gm.status = 'active'
WHERE e.expense_date BETWEEN $2 AND $3
  AND e.is_archived = FALSE
  AND (e.paid_by = $1 OR EXISTS (SELECT 1 FROM expense_splits es2 WHERE es2.expense_id = e.id AND es2.user_id = $1))
GROUP BY e.expense_date
ORDER BY e.expense_date ASC
`

type GetDashboardDailyParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type GetDashboardDailyRow struct {
	ExpenseDate  pgtype.Date    `json:"expense_date"`
	ExpenseCount int64          `json:"expense_count"`
	TotalAmount  pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) GetDashboardDaily(ctx context.Context, arg GetDashboardDailyParams) ([]GetDashboardDailyRow, error) {
	rows, err := q.db.Query(ctx, getDashboardDaily, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDashboardDailyRow
	for rows.Next() {
		var i GetDashboardDailyRow
		if err := rows.Scan(&i.ExpenseDate, &i.ExpenseCount, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardExpenseCount = `-- name: GetDashboardExpenseCount :one
SELECT COUNT(*)::bigint AS expense_count FROM (
    SELECT e.id FROM expenses e
    JOIN group_members gm ON gm.group_id = e.group_id AND gm.user_id = $1 AND gm.status = 'active'
    WHERE e.expense_date BETWEEN $2 AND $3
      AND e.is_archived = FALSE AND e.paid_by = $1
    UNION
    SELECT e.id FROM expenses e
    JOIN expense_splits es2 ON es2.expense_id = e.id AND es2.user_id = $1
    JOIN group_members gm ON gm.group_id = e.group_id AND gm.user_id = $1 AND gm.status = 'active'
    WHERE e.expense_date BETWEEN $2 AND $3
      AND e.is_archived = FALSE
) u
`

type GetDashboardExpenseCountParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

func (q *Queries) GetDashboardExpenseCount(ctx context.Context, arg GetDashboardExpenseCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getDashboardExpenseCount, arg.UserID, arg.FromDate, arg.ToDate)
	var expense_count int64
	err := row.Scan(&expense_count)
	return expense_count, err
}

const getDashboardOwedStats = `-- name: GetDashboardOwedStats :one
SELECT
    COALESCE(SUM(es.amount_owed), 0)::decimal(14,2) AS total_owed,
    COUNT(DISTINCT e.id)::bigint AS expense_count
FROM expense_splits es
JOIN expenses e ON e.id = es.expense_id
JOIN group_members gm ON gm.group_id = e.group_id AND gm.user_id = $1 AND gm.status = 'active'
WHERE es.user_id = $1
  AND e.expense_date BETWEEN $2 AND $3
  AND e.is_archived = FALSE
`

type GetDashboardOwedStatsParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type GetDashboardOwedStatsRow struct {
	TotalOwed    pgtype.Numeric `json:"total_owed"`
	ExpenseCount int64          `json:"expense_count"`
}

func (q *Queries) GetDashboardOwedStats(ctx context.Context, arg GetDashboardOwedStatsParams) (GetDashboardOwedStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardOwedStats, arg.UserID, arg.FromDate, arg.ToDate)
	var i GetDashboardOwedStatsRow
	err := row.Scan(&i.TotalOwed, &i.ExpenseCount)
	return i, err
}

const getDashboardPaidStats = `-- name: GetDashboardPaidStats :one
SELECT
    COUNT(*)::bigint AS expense_count,
    COALESCE(SUM(e.amount), 0)::decimal(14,2) AS total_amount
FROM expenses e
JOIN group_members gm ON gm.group_id = e.group_id AND gm.user_id = $1 AND gm.status = 'active'
WHERE e.paid_by = $1
  AND e.expense_date BETWEEN $2 AND $3
  AND e.is_archived = FALSE
`

type GetDashboardPaidStatsParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type GetDashboardPaidStatsRow struct {
	ExpenseCount int64          `json:"expense_count"`
	TotalAmount  pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) GetDashboardPaidStats(ctx context.Context, arg GetDashboardPaidStatsParams) (GetDashboardPaidStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardPaidStats, arg.UserID, arg.FromDate, arg.ToDate)
	var i GetDashboardPaidStatsRow
	err := row.Scan(&i.ExpenseCount, &i.TotalAmount)
	return i, err
}

const getDashboardRecent = `-- name: GetDashboardRecent :many
SELECT e.id, e.group_id, e.created_by, e.paid_by, e.category_id, e.amount, e.description, e.note, e.split_type, e.is_archived, e.archived_at, e.expense_date, e.splits_count, e.created_at, e.updated_at, g.name AS group_name
FROM expenses e
JOIN groups g ON g.id = e.group_id
JOIN group_members gm ON gm.group_id = e.group_id AND gm.user_id = $1 AND gm.status = 'active'
WHERE e.expense_date BETWEEN $2 AND $3
  AND e.is_archived = FALSE
  AND (e.paid_by = $1 OR EXISTS (SELECT 1 FROM expense_splits es2 WHERE es2.expense_id = e.id AND es2.user_id = $1))
ORDER BY e.expense_date DESC, e.created_at DESC
LIMIT 10
`

type GetDashboardRecentParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type GetDashboardRecentRow struct {
	ID          pgtype.UUID        `json:"id"`
	GroupID     pgtype.UUID        `json:"group_id"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	PaidBy      pgtype.UUID        `json:"paid_by"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Amount      pgtype.Numeric     `json:"amount"`
	Description pgtype.Text        `json:"description"`
	Note        pgtype.Text        `json:"note"`
	SplitType   SplitType          `json:"split_type"`
	IsArchived  bool               `json:"is_archived"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
	ExpenseDate pgtype.Date        `json:"expense_date"`
	SplitsCount int32              `json:"splits_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	GroupName   string             `json:"group_name"`
}

func (q *Queries) GetDashboardRecent(ctx context.Context, arg GetDashboardRecentParams) ([]GetDashboardRecentRow, error) {
	rows, err := q.db.Query(ctx, getDashboardRecent, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDashboardRecentRow
	for rows.Next() {
		var i GetDashboardRecentRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatedBy,
			&i.PaidBy,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.Note,
			&i.SplitType,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.ExpenseDate,
			&i.SplitsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardSettlementStats = `-- name: GetDashboardSettlementStats :one
SELECT
    COUNT(*)::bigint AS settlement_count,
    COALESCE(SUM(amount), 0)::decimal(14,2) AS settlement_amount
FROM settlements
WHERE (from_user_id = $1 OR to_user_id = $1)
  AND settlement_date BETWEEN $2 AND $3
  AND group_id IN (SELECT group_id FROM group_members WHERE group_members.user_id = $1 AND status = 'active')
`

type GetDashboardSettlementStatsParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type GetDashboardSettlementStatsRow struct {
	SettlementCount  int64          `json:"settlement_count"`
	SettlementAmount pgtype.Numeric `json:"settlement_amount"`
}

func (q *Queries) GetDashboardSettlementStats(ctx context.Context, arg GetDashboardSettlementStatsParams) (GetDashboardSettlementStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardSettlementStats, arg.UserID, arg.FromDate, arg.ToDate)
	var i GetDashboardSettlementStatsRow
	err := row.Scan(&i.SettlementCount, &i.SettlementAmount)
	return i, err
}

const getDashboardSettlementStatsUnion = `-- name: GetDashboardSettlementStatsUnion :one
SELECT COUNT(*)::bigint AS settlement_count, COALESCE(SUM(u.amount),0)::decimal(14,2) AS settlement_amount FROM (
    SELECT s.amount FROM settlements s WHERE s.from_user_id = $1 AND s.settlement_date BETWEEN $2 AND $3 AND s.group_id IN (SELECT group_id FROM group_members WHERE user_id = $1 AND status = 'active')
    UNION ALL
    SELECT s.amount FROM settlements s WHERE s.to_user_id = $1 AND s.settlement_date BETWEEN $2 AND $3 AND s.group_id IN (SELECT group_id FROM group_members WHERE user_id = $1 AND status = 'active')
) u
`

type GetDashboardSettlementStatsUnionParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type GetDashboardSettlementStatsUnionRow struct {
	SettlementCount  int64          `json:"settlement_count"`
	SettlementAmount pgtype.Numeric `json:"settlement_amount"`
}

func (q *Queries) GetDashboardSettlementStatsUnion(ctx context.Context, arg GetDashboardSettlementStatsUnionParams) (GetDashboardSettlementStatsUnionRow, error) {
	row := q.db.QueryRow(ctx, getDashboardSettlementStatsUnion, arg.UserID, arg.FromDate, arg.ToDate)
	var i GetDashboardSettlementStatsUnionRow
	err := row.Scan(&i.SettlementCount, &i.SettlementAmount)
	return i, err
}
