// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_login_codes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailLoginCode = `-- name: ConsumeEmailLoginCode :one
DELETE FROM email_login_codes
WHERE id = $1 AND expires_at > CURRENT_TIMESTAMP
RETURNING email
`

func (q *Queries) ConsumeEmailLoginCode(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, consumeEmailLoginCode, id)
	var email string
	err := row.Scan(&email)
	return email, err
}

const createEmailLoginCode = `-- name: CreateEmailLoginCode :one
INSERT INTO email_login_codes (
    email,
    expires_at
) VALUES (
    $1,
    $2
)
ON CONFLICT (email) DO UPDATE
SET expires_at = EXCLUDED.expires_at
WHERE email_login_codes.expires_at <= CURRENT_TIMESTAMP
RETURNING id, email, expires_at, created_at
`

type CreateEmailLoginCodeParams struct {
	Email     string             `json:"email"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Inserts a new code, or rotates an existing one only if it already expired.
// Returns no row (pgx.ErrNoRows) when an unexpired code is still on file.
func (q *Queries) CreateEmailLoginCode(ctx context.Context, arg CreateEmailLoginCodeParams) (EmailLoginCode, error) {
	row := q.db.QueryRow(ctx, createEmailLoginCode, arg.Email, arg.ExpiresAt)
	var i EmailLoginCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
