// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expense_splits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpenseSplit = `-- name: CreateExpenseSplit :one
INSERT INTO expense_splits (
    expense_id,
    user_id,
    amount_owed,
    percentage,
    shares
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, expense_id, user_id, amount_owed, percentage, shares, created_at, updated_at
`

type CreateExpenseSplitParams struct {
	ExpenseID  pgtype.UUID    `json:"expense_id"`
	UserID     pgtype.UUID    `json:"user_id"`
	AmountOwed pgtype.Numeric `json:"amount_owed"`
	Percentage pgtype.Numeric `json:"percentage"`
	Shares     pgtype.Numeric `json:"shares"`
}

func (q *Queries) CreateExpenseSplit(ctx context.Context, arg CreateExpenseSplitParams) (ExpenseSplit, error) {
	row := q.db.QueryRow(ctx, createExpenseSplit,
		arg.ExpenseID,
		arg.UserID,
		arg.AmountOwed,
		arg.Percentage,
		arg.Shares,
	)
	var i ExpenseSplit
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.UserID,
		&i.AmountOwed,
		&i.Percentage,
		&i.Shares,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpenseSplit = `-- name: DeleteExpenseSplit :exec
DELETE FROM expense_splits WHERE id = $1
`

func (q *Queries) DeleteExpenseSplit(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpenseSplit, id)
	return err
}

const deleteExpenseSplitsByExpenseID = `-- name: DeleteExpenseSplitsByExpenseID :exec
DELETE FROM expense_splits WHERE expense_id = $1
`

func (q *Queries) DeleteExpenseSplitsByExpenseID(ctx context.Context, expenseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpenseSplitsByExpenseID, expenseID)
	return err
}

const getExpenseSplitByExpenseAndUser = `-- name: GetExpenseSplitByExpenseAndUser :one
SELECT id, expense_id, user_id, amount_owed, percentage, shares, created_at, updated_at FROM expense_splits WHERE expense_id = $1 AND user_id = $2
`

type GetExpenseSplitByExpenseAndUserParams struct {
	ExpenseID pgtype.UUID `json:"expense_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetExpenseSplitByExpenseAndUser(ctx context.Context, arg GetExpenseSplitByExpenseAndUserParams) (ExpenseSplit, error) {
	row := q.db.QueryRow(ctx, getExpenseSplitByExpenseAndUser, arg.ExpenseID, arg.UserID)
	var i ExpenseSplit
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.UserID,
		&i.AmountOwed,
		&i.Percentage,
		&i.Shares,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenseSplitByID = `-- name: GetExpenseSplitByID :one
SELECT id, expense_id, user_id, amount_owed, percentage, shares, created_at, updated_at FROM expense_splits WHERE id = $1
`

func (q *Queries) GetExpenseSplitByID(ctx context.Context, id pgtype.UUID) (ExpenseSplit, error) {
	row := q.db.QueryRow(ctx, getExpenseSplitByID, id)
	var i ExpenseSplit
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.UserID,
		&i.AmountOwed,
		&i.Percentage,
		&i.Shares,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpenseSplitsByExpenseID = `-- name: ListExpenseSplitsByExpenseID :many
SELECT id, expense_id, user_id, amount_owed, percentage, shares, created_at, updated_at FROM expense_splits WHERE expense_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListExpenseSplitsByExpenseID(ctx context.Context, expenseID pgtype.UUID) ([]ExpenseSplit, error) {
	rows, err := q.db.Query(ctx, listExpenseSplitsByExpenseID, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseSplit
	for rows.Next() {
		var i ExpenseSplit
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.UserID,
			&i.AmountOwed,
			&i.Percentage,
			&i.Shares,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseSplitsByUserID = `-- name: ListExpenseSplitsByUserID :many
SELECT id, expense_id, user_id, amount_owed, percentage, shares, created_at, updated_at FROM expense_splits WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListExpenseSplitsByUserID(ctx context.Context, userID pgtype.UUID) ([]ExpenseSplit, error) {
	rows, err := q.db.Query(ctx, listExpenseSplitsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseSplit
	for rows.Next() {
		var i ExpenseSplit
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.UserID,
			&i.AmountOwed,
			&i.Percentage,
			&i.Shares,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpenseSplit = `-- name: UpdateExpenseSplit :one
UPDATE expense_splits SET
    amount_owed = COALESCE($1, amount_owed),
    percentage = COALESCE($2, percentage),
    shares = COALESCE($3, shares)
WHERE id = $4
RETURNING id, expense_id, user_id, amount_owed, percentage, shares, created_at, updated_at
`

type UpdateExpenseSplitParams struct {
	AmountOwed pgtype.Numeric `json:"amount_owed"`
	Percentage pgtype.Numeric `json:"percentage"`
	Shares     pgtype.Numeric `json:"shares"`
	ID         pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateExpenseSplit(ctx context.Context, arg UpdateExpenseSplitParams) (ExpenseSplit, error) {
	row := q.db.QueryRow(ctx, updateExpenseSplit,
		arg.AmountOwed,
		arg.Percentage,
		arg.Shares,
		arg.ID,
	)
	var i ExpenseSplit
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.UserID,
		&i.AmountOwed,
		&i.Percentage,
		&i.Shares,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
