// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveExpense = `-- name: ArchiveExpense :one
UPDATE expenses SET
    is_archived = TRUE,
    archived_at = NOW()
WHERE id = $1
RETURNING id, group_id, created_by, paid_by, category_id, amount, description, note, split_type, is_archived, archived_at, expense_date, created_at, updated_at
`

func (q *Queries) ArchiveExpense(ctx context.Context, id pgtype.UUID) (Expense, error) {
	row := q.db.QueryRow(ctx, archiveExpense, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.PaidBy,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.Note,
		&i.SplitType,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.ExpenseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (
    group_id,
    created_by,
    paid_by,
    category_id,
    amount,
    description,
    note,
    split_type,
    expense_date
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, group_id, created_by, paid_by, category_id, amount, description, note, split_type, is_archived, archived_at, expense_date, created_at, updated_at
`

type CreateExpenseParams struct {
	GroupID     pgtype.UUID
	CreatedBy   pgtype.UUID
	PaidBy      pgtype.UUID
	CategoryID  pgtype.UUID
	Amount      pgtype.Numeric
	Description pgtype.Text
	Note        pgtype.Text
	SplitType   SplitType
	ExpenseDate pgtype.Date
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.GroupID,
		arg.CreatedBy,
		arg.PaidBy,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.Note,
		arg.SplitType,
		arg.ExpenseDate,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.PaidBy,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.Note,
		&i.SplitType,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.ExpenseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses WHERE id = $1
`

func (q *Queries) DeleteExpense(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpense, id)
	return err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT id, group_id, created_by, paid_by, category_id, amount, description, note, split_type, is_archived, archived_at, expense_date, created_at, updated_at FROM expenses WHERE id = $1
`

func (q *Queries) GetExpenseByID(ctx context.Context, id pgtype.UUID) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpenseByID, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.PaidBy,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.Note,
		&i.SplitType,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.ExpenseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpensesByGroupAndCategory = `-- name: ListExpensesByGroupAndCategory :many
SELECT id, group_id, created_by, paid_by, category_id, amount, description, note, split_type, is_archived, archived_at, expense_date, created_at, updated_at FROM expenses
WHERE group_id = $1 AND category_id = $2 AND is_archived = FALSE
ORDER BY expense_date DESC, created_at DESC
`

type ListExpensesByGroupAndCategoryParams struct {
	GroupID    pgtype.UUID
	CategoryID pgtype.UUID
}

func (q *Queries) ListExpensesByGroupAndCategory(ctx context.Context, arg ListExpensesByGroupAndCategoryParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByGroupAndCategory, arg.GroupID, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatedBy,
			&i.PaidBy,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.Note,
			&i.SplitType,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.ExpenseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByGroupID = `-- name: ListExpensesByGroupID :many
SELECT id, group_id, created_by, paid_by, category_id, amount, description, note, split_type, is_archived, archived_at, expense_date, created_at, updated_at FROM expenses
WHERE group_id = $1 AND is_archived = FALSE
ORDER BY expense_date DESC, created_at DESC
`

func (q *Queries) ListExpensesByGroupID(ctx context.Context, groupID pgtype.UUID) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatedBy,
			&i.PaidBy,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.Note,
			&i.SplitType,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.ExpenseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByPaidBy = `-- name: ListExpensesByPaidBy :many
SELECT id, group_id, created_by, paid_by, category_id, amount, description, note, split_type, is_archived, archived_at, expense_date, created_at, updated_at FROM expenses
WHERE paid_by = $1 AND is_archived = FALSE
ORDER BY expense_date DESC, created_at DESC
`

func (q *Queries) ListExpensesByPaidBy(ctx context.Context, paidBy pgtype.UUID) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByPaidBy, paidBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatedBy,
			&i.PaidBy,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.Note,
			&i.SplitType,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.ExpenseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveExpense = `-- name: UnarchiveExpense :one
UPDATE expenses SET
    is_archived = FALSE,
    archived_at = NULL
WHERE id = $1
RETURNING id, group_id, created_by, paid_by, category_id, amount, description, note, split_type, is_archived, archived_at, expense_date, created_at, updated_at
`

func (q *Queries) UnarchiveExpense(ctx context.Context, id pgtype.UUID) (Expense, error) {
	row := q.db.QueryRow(ctx, unarchiveExpense, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.PaidBy,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.Note,
		&i.SplitType,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.ExpenseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses SET
    paid_by = COALESCE($1, paid_by),
    category_id = COALESCE($2, category_id),
    amount = COALESCE($3, amount),
    description = COALESCE($4, description),
    note = COALESCE($5, note),
    split_type = COALESCE($6, split_type),
    expense_date = COALESCE($7, expense_date)
WHERE id = $8
RETURNING id, group_id, created_by, paid_by, category_id, amount, description, note, split_type, is_archived, archived_at, expense_date, created_at, updated_at
`

type UpdateExpenseParams struct {
	PaidBy      pgtype.UUID
	CategoryID  pgtype.UUID
	Amount      pgtype.Numeric
	Description pgtype.Text
	Note        pgtype.Text
	SplitType   NullSplitType
	ExpenseDate pgtype.Date
	ID          pgtype.UUID
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.PaidBy,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
		arg.Note,
		arg.SplitType,
		arg.ExpenseDate,
		arg.ID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreatedBy,
		&i.PaidBy,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.Note,
		&i.SplitType,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.ExpenseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
