// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group_budgets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroupBudget = `-- name: CreateGroupBudget :one
INSERT INTO group_budgets (
    group_id,
    amount_limit,
    period,
    start_date,
    end_date,
    alert_threshold
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, group_id, amount_limit, period, start_date, end_date, alert_threshold, created_at, updated_at
`

type CreateGroupBudgetParams struct {
	GroupID        pgtype.UUID    `json:"group_id"`
	AmountLimit    pgtype.Numeric `json:"amount_limit"`
	Period         BudgetPeriod   `json:"period"`
	StartDate      pgtype.Date    `json:"start_date"`
	EndDate        pgtype.Date    `json:"end_date"`
	AlertThreshold int32          `json:"alert_threshold"`
}

func (q *Queries) CreateGroupBudget(ctx context.Context, arg CreateGroupBudgetParams) (GroupBudget, error) {
	row := q.db.QueryRow(ctx, createGroupBudget,
		arg.GroupID,
		arg.AmountLimit,
		arg.Period,
		arg.StartDate,
		arg.EndDate,
		arg.AlertThreshold,
	)
	var i GroupBudget
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.AmountLimit,
		&i.Period,
		&i.StartDate,
		&i.EndDate,
		&i.AlertThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroupBudget = `-- name: DeleteGroupBudget :exec
DELETE FROM group_budgets WHERE id = $1
`

func (q *Queries) DeleteGroupBudget(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroupBudget, id)
	return err
}

const getGroupBudgetByID = `-- name: GetGroupBudgetByID :one
SELECT id, group_id, amount_limit, period, start_date, end_date, alert_threshold, created_at, updated_at FROM group_budgets WHERE id = $1
`

func (q *Queries) GetGroupBudgetByID(ctx context.Context, id pgtype.UUID) (GroupBudget, error) {
	row := q.db.QueryRow(ctx, getGroupBudgetByID, id)
	var i GroupBudget
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.AmountLimit,
		&i.Period,
		&i.StartDate,
		&i.EndDate,
		&i.AlertThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroupBudgetsByGroupID = `-- name: ListGroupBudgetsByGroupID :many
SELECT id, group_id, amount_limit, period, start_date, end_date, alert_threshold, created_at, updated_at FROM group_budgets WHERE group_id = $1 ORDER BY start_date DESC
`

func (q *Queries) ListGroupBudgetsByGroupID(ctx context.Context, groupID pgtype.UUID) ([]GroupBudget, error) {
	rows, err := q.db.Query(ctx, listGroupBudgetsByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupBudget
	for rows.Next() {
		var i GroupBudget
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.AmountLimit,
			&i.Period,
			&i.StartDate,
			&i.EndDate,
			&i.AlertThreshold,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupBudget = `-- name: UpdateGroupBudget :one
UPDATE group_budgets SET
    amount_limit = COALESCE($1, amount_limit),
    period = COALESCE($2, period),
    start_date = COALESCE($3, start_date),
    end_date = COALESCE($4, end_date),
    alert_threshold = COALESCE($5, alert_threshold)
WHERE id = $6
RETURNING id, group_id, amount_limit, period, start_date, end_date, alert_threshold, created_at, updated_at
`

type UpdateGroupBudgetParams struct {
	AmountLimit    pgtype.Numeric   `json:"amount_limit"`
	Period         NullBudgetPeriod `json:"period"`
	StartDate      pgtype.Date      `json:"start_date"`
	EndDate        pgtype.Date      `json:"end_date"`
	AlertThreshold pgtype.Int4      `json:"alert_threshold"`
	ID             pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateGroupBudget(ctx context.Context, arg UpdateGroupBudgetParams) (GroupBudget, error) {
	row := q.db.QueryRow(ctx, updateGroupBudget,
		arg.AmountLimit,
		arg.Period,
		arg.StartDate,
		arg.EndDate,
		arg.AlertThreshold,
		arg.ID,
	)
	var i GroupBudget
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.AmountLimit,
		&i.Period,
		&i.StartDate,
		&i.EndDate,
		&i.AlertThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
