// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group_members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateGroupMember = `-- name: ActivateGroupMember :one
UPDATE group_members SET
    status = 'active',
    joined_at = NOW()
WHERE id = $1
RETURNING id, user_id, group_id, role, status, invited_by, joined_at, left_at, created_at, updated_at
`

func (q *Queries) ActivateGroupMember(ctx context.Context, id pgtype.UUID) (GroupMember, error) {
	row := q.db.QueryRow(ctx, activateGroupMember, id)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGroupMember = `-- name: CreateGroupMember :one
INSERT INTO group_members (
    user_id,
    group_id,
    role,
    status,
    invited_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, user_id, group_id, role, status, invited_by, joined_at, left_at, created_at, updated_at
`

type CreateGroupMemberParams struct {
	UserID    pgtype.UUID       `json:"user_id"`
	GroupID   pgtype.UUID       `json:"group_id"`
	Role      GroupMemberRole   `json:"role"`
	Status    GroupMemberStatus `json:"status"`
	InvitedBy pgtype.UUID       `json:"invited_by"`
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, createGroupMember,
		arg.UserID,
		arg.GroupID,
		arg.Role,
		arg.Status,
		arg.InvitedBy,
	)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroupMember = `-- name: DeleteGroupMember :exec
DELETE FROM group_members WHERE id = $1
`

func (q *Queries) DeleteGroupMember(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroupMember, id)
	return err
}

const getGroupMemberByID = `-- name: GetGroupMemberByID :one
SELECT id, user_id, group_id, role, status, invited_by, joined_at, left_at, created_at, updated_at FROM group_members WHERE id = $1
`

func (q *Queries) GetGroupMemberByID(ctx context.Context, id pgtype.UUID) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMemberByID, id)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupMemberByUserAndGroup = `-- name: GetGroupMemberByUserAndGroup :one
SELECT id, user_id, group_id, role, status, invited_by, joined_at, left_at, created_at, updated_at FROM group_members WHERE user_id = $1 AND group_id = $2
`

type GetGroupMemberByUserAndGroupParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) GetGroupMemberByUserAndGroup(ctx context.Context, arg GetGroupMemberByUserAndGroupParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMemberByUserAndGroup, arg.UserID, arg.GroupID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const leaveGroupMember = `-- name: LeaveGroupMember :one
UPDATE group_members SET
    status = 'left',
    left_at = NOW()
WHERE id = $1
RETURNING id, user_id, group_id, role, status, invited_by, joined_at, left_at, created_at, updated_at
`

func (q *Queries) LeaveGroupMember(ctx context.Context, id pgtype.UUID) (GroupMember, error) {
	row := q.db.QueryRow(ctx, leaveGroupMember, id)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroupMembersByGroupAndStatus = `-- name: ListGroupMembersByGroupAndStatus :many
SELECT id, user_id, group_id, role, status, invited_by, joined_at, left_at, created_at, updated_at FROM group_members WHERE group_id = $1 AND status = $2 ORDER BY created_at ASC
LIMIT $4 OFFSET $3
`

type ListGroupMembersByGroupAndStatusParams struct {
	GroupID    pgtype.UUID       `json:"group_id"`
	Status     GroupMemberStatus `json:"status"`
	PageOffset int32             `json:"page_offset"`
	PageLimit  int32             `json:"page_limit"`
}

func (q *Queries) ListGroupMembersByGroupAndStatus(ctx context.Context, arg ListGroupMembersByGroupAndStatusParams) ([]GroupMember, error) {
	rows, err := q.db.Query(ctx, listGroupMembersByGroupAndStatus,
		arg.GroupID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupMember
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Role,
			&i.Status,
			&i.InvitedBy,
			&i.JoinedAt,
			&i.LeftAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembersByGroupID = `-- name: ListGroupMembersByGroupID :many
SELECT id, user_id, group_id, role, status, invited_by, joined_at, left_at, created_at, updated_at FROM group_members WHERE group_id = $1 ORDER BY created_at ASC
LIMIT $3 OFFSET $2
`

type ListGroupMembersByGroupIDParams struct {
	GroupID    pgtype.UUID `json:"group_id"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

func (q *Queries) ListGroupMembersByGroupID(ctx context.Context, arg ListGroupMembersByGroupIDParams) ([]GroupMember, error) {
	rows, err := q.db.Query(ctx, listGroupMembersByGroupID, arg.GroupID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupMember
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Role,
			&i.Status,
			&i.InvitedBy,
			&i.JoinedAt,
			&i.LeftAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :one
UPDATE group_members SET
    status = 'removed',
    left_at = NOW()
WHERE id = $1
RETURNING id, user_id, group_id, role, status, invited_by, joined_at, left_at, created_at, updated_at
`

func (q *Queries) RemoveGroupMember(ctx context.Context, id pgtype.UUID) (GroupMember, error) {
	row := q.db.QueryRow(ctx, removeGroupMember, id)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGroupMemberRole = `-- name: UpdateGroupMemberRole :one
UPDATE group_members SET
    role = $2
WHERE id = $1
RETURNING id, user_id, group_id, role, status, invited_by, joined_at, left_at, created_at, updated_at
`

type UpdateGroupMemberRoleParams struct {
	ID   pgtype.UUID     `json:"id"`
	Role GroupMemberRole `json:"role"`
}

func (q *Queries) UpdateGroupMemberRole(ctx context.Context, arg UpdateGroupMemberRoleParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, updateGroupMemberRole, arg.ID, arg.Role)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.LeftAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
