// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group_members_with_user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listGroupMembersWithUser = `-- name: ListGroupMembersWithUser :many
SELECT
    gm.id,
    gm.user_id,
    gm.group_id,
    gm.role,
    gm.status,
    gm.invited_by,
    gm.joined_at,
    gm.left_at,
    gm.created_at,
    gm.updated_at,
    u.first_name,
    u.last_name,
    u.email,
    u.avatar_url
FROM group_members gm
JOIN users u ON u.id = gm.user_id
WHERE gm.group_id = $1
ORDER BY gm.created_at ASC
`

type ListGroupMembersWithUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	Role      GroupMemberRole    `json:"role"`
	Status    GroupMemberStatus  `json:"status"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
	LeftAt    pgtype.Timestamptz `json:"left_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	FirstName string             `json:"first_name"`
	LastName  pgtype.Text        `json:"last_name"`
	Email     string             `json:"email"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) ListGroupMembersWithUser(ctx context.Context, groupID pgtype.UUID) ([]ListGroupMembersWithUserRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembersWithUser, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersWithUserRow
	for rows.Next() {
		var i ListGroupMembersWithUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Role,
			&i.Status,
			&i.InvitedBy,
			&i.JoinedAt,
			&i.LeftAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
