// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveGroup = `-- name: ArchiveGroup :one
UPDATE groups SET
    is_archived = TRUE,
    archived_at = NOW()
WHERE id = $1
RETURNING id, name, description, avatar_url, type, default_currency, created_by, is_archived, archived_at, created_at, updated_at
`

func (q *Queries) ArchiveGroup(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, archiveGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.Type,
		&i.DefaultCurrency,
		&i.CreatedBy,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (
    name,
    description,
    avatar_url,
    type,
    default_currency,
    created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, name, description, avatar_url, type, default_currency, created_by, is_archived, archived_at, created_at, updated_at
`

type CreateGroupParams struct {
	Name            string
	Description     pgtype.Text
	AvatarUrl       pgtype.Text
	Type            GroupType
	DefaultCurrency string
	CreatedBy       pgtype.UUID
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.Description,
		arg.AvatarUrl,
		arg.Type,
		arg.DefaultCurrency,
		arg.CreatedBy,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.Type,
		&i.DefaultCurrency,
		&i.CreatedBy,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, description, avatar_url, type, default_currency, created_by, is_archived, archived_at, created_at, updated_at FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.Type,
		&i.DefaultCurrency,
		&i.CreatedBy,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroupsByUserID = `-- name: ListGroupsByUserID :many
SELECT g.id, g.name, g.description, g.avatar_url, g.type, g.default_currency, g.created_by, g.is_archived, g.archived_at, g.created_at, g.updated_at FROM groups g
INNER JOIN group_members gm ON gm.group_id = g.id
WHERE gm.user_id = $1 AND gm.status = 'active'
ORDER BY g.created_at DESC
`

func (q *Queries) ListGroupsByUserID(ctx context.Context, userID pgtype.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AvatarUrl,
			&i.Type,
			&i.DefaultCurrency,
			&i.CreatedBy,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveGroup = `-- name: UnarchiveGroup :one
UPDATE groups SET
    is_archived = FALSE,
    archived_at = NULL
WHERE id = $1
RETURNING id, name, description, avatar_url, type, default_currency, created_by, is_archived, archived_at, created_at, updated_at
`

func (q *Queries) UnarchiveGroup(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, unarchiveGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.Type,
		&i.DefaultCurrency,
		&i.CreatedBy,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    avatar_url = COALESCE($3, avatar_url),
    type = COALESCE($4, type),
    default_currency = COALESCE($5, default_currency)
WHERE id = $6
RETURNING id, name, description, avatar_url, type, default_currency, created_by, is_archived, archived_at, created_at, updated_at
`

type UpdateGroupParams struct {
	Name            pgtype.Text
	Description     pgtype.Text
	AvatarUrl       pgtype.Text
	Type            NullGroupType
	DefaultCurrency pgtype.Text
	ID              pgtype.UUID
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.Name,
		arg.Description,
		arg.AvatarUrl,
		arg.Type,
		arg.DefaultCurrency,
		arg.ID,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.Type,
		&i.DefaultCurrency,
		&i.CreatedBy,
		&i.IsArchived,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
