// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE invitations SET
    status = 'accepted',
    accepted_at = NOW()
WHERE id = $1
RETURNING id, group_id, invited_by, email, token_hash, status, expires_at, accepted_at, rejected_at, created_at, updated_at
`

func (q *Queries) AcceptInvitation(ctx context.Context, id pgtype.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, acceptInvitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.InvitedBy,
		&i.Email,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RejectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelInvitation = `-- name: CancelInvitation :one
UPDATE invitations SET
    status = 'cancelled'
WHERE id = $1
RETURNING id, group_id, invited_by, email, token_hash, status, expires_at, accepted_at, rejected_at, created_at, updated_at
`

func (q *Queries) CancelInvitation(ctx context.Context, id pgtype.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, cancelInvitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.InvitedBy,
		&i.Email,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RejectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (
    group_id,
    invited_by,
    email,
    token_hash,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, group_id, invited_by, email, token_hash, status, expires_at, accepted_at, rejected_at, created_at, updated_at
`

type CreateInvitationParams struct {
	GroupID   pgtype.UUID        `json:"group_id"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	Email     string             `json:"email"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.GroupID,
		arg.InvitedBy,
		arg.Email,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.InvitedBy,
		&i.Email,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RejectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM invitations WHERE id = $1
`

func (q *Queries) DeleteInvitation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvitation, id)
	return err
}

const expireOverdueInvitations = `-- name: ExpireOverdueInvitations :exec
UPDATE invitations SET
    status = 'expired'
WHERE status = 'pending' AND expires_at < NOW()
`

func (q *Queries) ExpireOverdueInvitations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireOverdueInvitations)
	return err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, group_id, invited_by, email, token_hash, status, expires_at, accepted_at, rejected_at, created_at, updated_at FROM invitations WHERE id = $1
`

func (q *Queries) GetInvitationByID(ctx context.Context, id pgtype.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.InvitedBy,
		&i.Email,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RejectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT id, group_id, invited_by, email, token_hash, status, expires_at, accepted_at, rejected_at, created_at, updated_at FROM invitations WHERE token_hash = $1
`

func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.InvitedBy,
		&i.Email,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RejectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvitationsByGroupID = `-- name: ListInvitationsByGroupID :many
SELECT id, group_id, invited_by, email, token_hash, status, expires_at, accepted_at, rejected_at, created_at, updated_at FROM invitations WHERE group_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListInvitationsByGroupID(ctx context.Context, groupID pgtype.UUID) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitationsByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.InvitedBy,
			&i.Email,
			&i.TokenHash,
			&i.Status,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.RejectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitationsByEmail = `-- name: ListPendingInvitationsByEmail :many
SELECT id, group_id, invited_by, email, token_hash, status, expires_at, accepted_at, rejected_at, created_at, updated_at FROM invitations
WHERE LOWER(email) = LOWER($1) AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvitationsByEmail(ctx context.Context, lower string) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsByEmail, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.InvitedBy,
			&i.Email,
			&i.TokenHash,
			&i.Status,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.RejectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectInvitation = `-- name: RejectInvitation :one
UPDATE invitations SET
    status = 'rejected',
    rejected_at = NOW()
WHERE id = $1
RETURNING id, group_id, invited_by, email, token_hash, status, expires_at, accepted_at, rejected_at, created_at, updated_at
`

func (q *Queries) RejectInvitation(ctx context.Context, id pgtype.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, rejectInvitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.InvitedBy,
		&i.Email,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RejectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
