// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BudgetPeriod string

const (
	BudgetPeriodWeekly  BudgetPeriod = "weekly"
	BudgetPeriodMonthly BudgetPeriod = "monthly"
	BudgetPeriodYearly  BudgetPeriod = "yearly"
	BudgetPeriodCustom  BudgetPeriod = "custom"
)

func (e *BudgetPeriod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BudgetPeriod(s)
	case string:
		*e = BudgetPeriod(s)
	default:
		return fmt.Errorf("unsupported scan type for BudgetPeriod: %T", src)
	}
	return nil
}

type NullBudgetPeriod struct {
	BudgetPeriod BudgetPeriod
	Valid        bool // Valid is true if BudgetPeriod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBudgetPeriod) Scan(value interface{}) error {
	if value == nil {
		ns.BudgetPeriod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BudgetPeriod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBudgetPeriod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BudgetPeriod), nil
}

type GroupMemberRole string

const (
	GroupMemberRoleOwner  GroupMemberRole = "owner"
	GroupMemberRoleAdmin  GroupMemberRole = "admin"
	GroupMemberRoleMember GroupMemberRole = "member"
)

func (e *GroupMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupMemberRole(s)
	case string:
		*e = GroupMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupMemberRole: %T", src)
	}
	return nil
}

type NullGroupMemberRole struct {
	GroupMemberRole GroupMemberRole
	Valid           bool // Valid is true if GroupMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.GroupMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupMemberRole), nil
}

type GroupMemberStatus string

const (
	GroupMemberStatusInvited GroupMemberStatus = "invited"
	GroupMemberStatusActive  GroupMemberStatus = "active"
	GroupMemberStatusLeft    GroupMemberStatus = "left"
	GroupMemberStatusRemoved GroupMemberStatus = "removed"
)

func (e *GroupMemberStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupMemberStatus(s)
	case string:
		*e = GroupMemberStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupMemberStatus: %T", src)
	}
	return nil
}

type NullGroupMemberStatus struct {
	GroupMemberStatus GroupMemberStatus
	Valid             bool // Valid is true if GroupMemberStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupMemberStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GroupMemberStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupMemberStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupMemberStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupMemberStatus), nil
}

type GroupType string

const (
	GroupTypeHousehold GroupType = "household"
	GroupTypeTrip      GroupType = "trip"
	GroupTypeRoommates GroupType = "roommates"
	GroupTypeCouple    GroupType = "couple"
	GroupTypeProject   GroupType = "project"
	GroupTypeOther     GroupType = "other"
)

func (e *GroupType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupType(s)
	case string:
		*e = GroupType(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupType: %T", src)
	}
	return nil
}

type NullGroupType struct {
	GroupType GroupType
	Valid     bool // Valid is true if GroupType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupType) Scan(value interface{}) error {
	if value == nil {
		ns.GroupType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupType), nil
}

type InvitationStatus string

const (
	InvitationStatusPending   InvitationStatus = "pending"
	InvitationStatusAccepted  InvitationStatus = "accepted"
	InvitationStatusRejected  InvitationStatus = "rejected"
	InvitationStatusExpired   InvitationStatus = "expired"
	InvitationStatusCancelled InvitationStatus = "cancelled"
)

func (e *InvitationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvitationStatus(s)
	case string:
		*e = InvitationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvitationStatus: %T", src)
	}
	return nil
}

type NullInvitationStatus struct {
	InvitationStatus InvitationStatus
	Valid            bool // Valid is true if InvitationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvitationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvitationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvitationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvitationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvitationStatus), nil
}

type LoginProvider string

const (
	LoginProviderEmail  LoginProvider = "email"
	LoginProviderGoogle LoginProvider = "google"
)

func (e *LoginProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LoginProvider(s)
	case string:
		*e = LoginProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for LoginProvider: %T", src)
	}
	return nil
}

type NullLoginProvider struct {
	LoginProvider LoginProvider
	Valid         bool // Valid is true if LoginProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLoginProvider) Scan(value interface{}) error {
	if value == nil {
		ns.LoginProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LoginProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLoginProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LoginProvider), nil
}

type PaymentMethod string

const (
	PaymentMethodCash         PaymentMethod = "cash"
	PaymentMethodUpi          PaymentMethod = "upi"
	PaymentMethodBankTransfer PaymentMethod = "bank_transfer"
	PaymentMethodCard         PaymentMethod = "card"
	PaymentMethodOther        PaymentMethod = "other"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod
	Valid         bool // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type SplitType string

const (
	SplitTypeEqual      SplitType = "equal"
	SplitTypePercentage SplitType = "percentage"
	SplitTypeExact      SplitType = "exact"
	SplitTypeShares     SplitType = "shares"
)

func (e *SplitType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SplitType(s)
	case string:
		*e = SplitType(s)
	default:
		return fmt.Errorf("unsupported scan type for SplitType: %T", src)
	}
	return nil
}

type NullSplitType struct {
	SplitType SplitType
	Valid     bool // Valid is true if SplitType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSplitType) Scan(value interface{}) error {
	if value == nil {
		ns.SplitType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SplitType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSplitType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SplitType), nil
}

type Auth struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	Provider          NullLoginProvider
	ProviderAccountID string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Category struct {
	ID        pgtype.UUID
	GroupID   pgtype.UUID
	CreatedBy pgtype.UUID
	Name      string
	Icon      pgtype.Text
	Color     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Expense struct {
	ID          pgtype.UUID
	GroupID     pgtype.UUID
	CreatedBy   pgtype.UUID
	PaidBy      pgtype.UUID
	CategoryID  pgtype.UUID
	Amount      pgtype.Numeric
	Description pgtype.Text
	Note        pgtype.Text
	SplitType   SplitType
	IsArchived  bool
	ArchivedAt  pgtype.Timestamptz
	ExpenseDate pgtype.Date
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ExpenseSplit struct {
	ID         pgtype.UUID
	ExpenseID  pgtype.UUID
	UserID     pgtype.UUID
	AmountOwed pgtype.Numeric
	Percentage pgtype.Numeric
	Shares     pgtype.Numeric
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Group struct {
	ID              pgtype.UUID
	Name            string
	Description     pgtype.Text
	AvatarUrl       pgtype.Text
	Type            GroupType
	DefaultCurrency string
	CreatedBy       pgtype.UUID
	IsArchived      bool
	ArchivedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type GroupBudget struct {
	ID             pgtype.UUID
	GroupID        pgtype.UUID
	AmountLimit    pgtype.Numeric
	Period         BudgetPeriod
	StartDate      pgtype.Date
	EndDate        pgtype.Date
	AlertThreshold int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type GroupMember struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	GroupID   pgtype.UUID
	Role      GroupMemberRole
	Status    GroupMemberStatus
	InvitedBy pgtype.UUID
	JoinedAt  pgtype.Timestamptz
	LeftAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Invitation struct {
	ID         pgtype.UUID
	GroupID    pgtype.UUID
	InvitedBy  pgtype.UUID
	Email      string
	TokenHash  string
	Status     InvitationStatus
	ExpiresAt  pgtype.Timestamptz
	AcceptedAt pgtype.Timestamptz
	RejectedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type PersonalBudget struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	AmountLimit    pgtype.Numeric
	Period         BudgetPeriod
	StartDate      pgtype.Date
	EndDate        pgtype.Date
	AlertThreshold int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Settlement struct {
	ID             pgtype.UUID
	GroupID        pgtype.UUID
	FromUserID     pgtype.UUID
	ToUserID       pgtype.UUID
	Amount         pgtype.Numeric
	PaymentMethod  PaymentMethod
	Note           pgtype.Text
	SettlementDate pgtype.Date
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type SettlementSplit struct {
	ID             pgtype.UUID
	SettlementID   pgtype.UUID
	ExpenseSplitID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	Email           string
	FirstName       string
	LastName        pgtype.Text
	AvatarUrl       pgtype.Text
	IsActive        bool
	Timezone        string
	EmailVerifiedAt pgtype.Timestamptz
	LastLoginMode   NullLoginProvider
	LastLoginAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
