// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BudgetPeriod string

const (
	BudgetPeriodWeekly  BudgetPeriod = "weekly"
	BudgetPeriodMonthly BudgetPeriod = "monthly"
	BudgetPeriodYearly  BudgetPeriod = "yearly"
	BudgetPeriodCustom  BudgetPeriod = "custom"
)

func (e *BudgetPeriod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BudgetPeriod(s)
	case string:
		*e = BudgetPeriod(s)
	default:
		return fmt.Errorf("unsupported scan type for BudgetPeriod: %T", src)
	}
	return nil
}

type NullBudgetPeriod struct {
	BudgetPeriod BudgetPeriod `json:"budget_period"`
	Valid        bool         `json:"valid"` // Valid is true if BudgetPeriod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBudgetPeriod) Scan(value interface{}) error {
	if value == nil {
		ns.BudgetPeriod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BudgetPeriod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBudgetPeriod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BudgetPeriod), nil
}

type GroupMemberRole string

const (
	GroupMemberRoleOwner  GroupMemberRole = "owner"
	GroupMemberRoleAdmin  GroupMemberRole = "admin"
	GroupMemberRoleMember GroupMemberRole = "member"
)

func (e *GroupMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupMemberRole(s)
	case string:
		*e = GroupMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupMemberRole: %T", src)
	}
	return nil
}

type NullGroupMemberRole struct {
	GroupMemberRole GroupMemberRole `json:"group_member_role"`
	Valid           bool            `json:"valid"` // Valid is true if GroupMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.GroupMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupMemberRole), nil
}

type GroupMemberStatus string

const (
	GroupMemberStatusInvited GroupMemberStatus = "invited"
	GroupMemberStatusActive  GroupMemberStatus = "active"
	GroupMemberStatusLeft    GroupMemberStatus = "left"
	GroupMemberStatusRemoved GroupMemberStatus = "removed"
)

func (e *GroupMemberStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupMemberStatus(s)
	case string:
		*e = GroupMemberStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupMemberStatus: %T", src)
	}
	return nil
}

type NullGroupMemberStatus struct {
	GroupMemberStatus GroupMemberStatus `json:"group_member_status"`
	Valid             bool              `json:"valid"` // Valid is true if GroupMemberStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupMemberStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GroupMemberStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupMemberStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupMemberStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupMemberStatus), nil
}

type GroupType string

const (
	GroupTypeHousehold GroupType = "household"
	GroupTypeTrip      GroupType = "trip"
	GroupTypeRoommates GroupType = "roommates"
	GroupTypeCouple    GroupType = "couple"
	GroupTypeProject   GroupType = "project"
	GroupTypeOther     GroupType = "other"
)

func (e *GroupType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupType(s)
	case string:
		*e = GroupType(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupType: %T", src)
	}
	return nil
}

type NullGroupType struct {
	GroupType GroupType `json:"group_type"`
	Valid     bool      `json:"valid"` // Valid is true if GroupType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupType) Scan(value interface{}) error {
	if value == nil {
		ns.GroupType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupType), nil
}

type InvitationStatus string

const (
	InvitationStatusPending   InvitationStatus = "pending"
	InvitationStatusAccepted  InvitationStatus = "accepted"
	InvitationStatusRejected  InvitationStatus = "rejected"
	InvitationStatusExpired   InvitationStatus = "expired"
	InvitationStatusCancelled InvitationStatus = "cancelled"
)

func (e *InvitationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvitationStatus(s)
	case string:
		*e = InvitationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvitationStatus: %T", src)
	}
	return nil
}

type NullInvitationStatus struct {
	InvitationStatus InvitationStatus `json:"invitation_status"`
	Valid            bool             `json:"valid"` // Valid is true if InvitationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvitationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvitationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvitationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvitationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvitationStatus), nil
}

type LoginProvider string

const (
	LoginProviderEmail  LoginProvider = "email"
	LoginProviderGoogle LoginProvider = "google"
)

func (e *LoginProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LoginProvider(s)
	case string:
		*e = LoginProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for LoginProvider: %T", src)
	}
	return nil
}

type NullLoginProvider struct {
	LoginProvider LoginProvider `json:"login_provider"`
	Valid         bool          `json:"valid"` // Valid is true if LoginProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLoginProvider) Scan(value interface{}) error {
	if value == nil {
		ns.LoginProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LoginProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLoginProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LoginProvider), nil
}

type PaymentMethod string

const (
	PaymentMethodCash         PaymentMethod = "cash"
	PaymentMethodUpi          PaymentMethod = "upi"
	PaymentMethodBankTransfer PaymentMethod = "bank_transfer"
	PaymentMethodCard         PaymentMethod = "card"
	PaymentMethodOther        PaymentMethod = "other"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type SplitType string

const (
	SplitTypeEqual      SplitType = "equal"
	SplitTypePercentage SplitType = "percentage"
	SplitTypeExact      SplitType = "exact"
	SplitTypeShares     SplitType = "shares"
)

func (e *SplitType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SplitType(s)
	case string:
		*e = SplitType(s)
	default:
		return fmt.Errorf("unsupported scan type for SplitType: %T", src)
	}
	return nil
}

type NullSplitType struct {
	SplitType SplitType `json:"split_type"`
	Valid     bool      `json:"valid"` // Valid is true if SplitType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSplitType) Scan(value interface{}) error {
	if value == nil {
		ns.SplitType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SplitType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSplitType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SplitType), nil
}

type Auth struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Provider          NullLoginProvider  `json:"provider"`
	ProviderAccountID string             `json:"provider_account_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	Name      string             `json:"name"`
	Icon      pgtype.Text        `json:"icon"`
	Color     string             `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type EmailLoginCode struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Expense struct {
	ID          pgtype.UUID        `json:"id"`
	GroupID     pgtype.UUID        `json:"group_id"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	PaidBy      pgtype.UUID        `json:"paid_by"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Amount      pgtype.Numeric     `json:"amount"`
	Description pgtype.Text        `json:"description"`
	Note        pgtype.Text        `json:"note"`
	SplitType   SplitType          `json:"split_type"`
	IsArchived  bool               `json:"is_archived"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
	ExpenseDate pgtype.Date        `json:"expense_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ExpenseSplit struct {
	ID         pgtype.UUID        `json:"id"`
	ExpenseID  pgtype.UUID        `json:"expense_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	AmountOwed pgtype.Numeric     `json:"amount_owed"`
	Percentage pgtype.Numeric     `json:"percentage"`
	Shares     pgtype.Numeric     `json:"shares"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Group struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	Type            GroupType          `json:"type"`
	DefaultCurrency string             `json:"default_currency"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	IsArchived      bool               `json:"is_archived"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type GroupBudget struct {
	ID             pgtype.UUID        `json:"id"`
	GroupID        pgtype.UUID        `json:"group_id"`
	AmountLimit    pgtype.Numeric     `json:"amount_limit"`
	Period         BudgetPeriod       `json:"period"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	AlertThreshold int32              `json:"alert_threshold"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type GroupMember struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	Role      GroupMemberRole    `json:"role"`
	Status    GroupMemberStatus  `json:"status"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
	LeftAt    pgtype.Timestamptz `json:"left_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Invitation struct {
	ID         pgtype.UUID        `json:"id"`
	GroupID    pgtype.UUID        `json:"group_id"`
	InvitedBy  pgtype.UUID        `json:"invited_by"`
	Email      string             `json:"email"`
	TokenHash  string             `json:"token_hash"`
	Status     InvitationStatus   `json:"status"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	RejectedAt pgtype.Timestamptz `json:"rejected_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type PersonalBudget struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	AmountLimit    pgtype.Numeric     `json:"amount_limit"`
	Period         BudgetPeriod       `json:"period"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	AlertThreshold int32              `json:"alert_threshold"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Settlement struct {
	ID             pgtype.UUID        `json:"id"`
	GroupID        pgtype.UUID        `json:"group_id"`
	FromUserID     pgtype.UUID        `json:"from_user_id"`
	ToUserID       pgtype.UUID        `json:"to_user_id"`
	Amount         pgtype.Numeric     `json:"amount"`
	PaymentMethod  PaymentMethod      `json:"payment_method"`
	Note           pgtype.Text        `json:"note"`
	SettlementDate pgtype.Date        `json:"settlement_date"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type SettlementSplit struct {
	ID             pgtype.UUID        `json:"id"`
	SettlementID   pgtype.UUID        `json:"settlement_id"`
	ExpenseSplitID pgtype.UUID        `json:"expense_split_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	FirstName       string             `json:"first_name"`
	LastName        pgtype.Text        `json:"last_name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	IsActive        bool               `json:"is_active"`
	Timezone        string             `json:"timezone"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	LastLoginMode   NullLoginProvider  `json:"last_login_mode"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
