// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: overview.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOverviewByCategory = `-- name: GetOverviewByCategory :many
SELECT
    c.id AS category_id,
    c.name AS category_name,
    c.color AS category_color,
    c.icon AS category_icon,
    COUNT(e.id)::bigint AS expense_count,
    COALESCE(SUM(e.amount), 0)::decimal(14,2) AS total_amount
FROM expenses e
LEFT JOIN categories c ON c.id = e.category_id
WHERE e.group_id = $1
  AND e.expense_date BETWEEN $2 AND $3
  AND e.is_archived = FALSE
GROUP BY c.id, c.name, c.color, c.icon
ORDER BY total_amount DESC
`

type GetOverviewByCategoryParams struct {
	GroupID       pgtype.UUID `json:"group_id"`
	ExpenseDate   pgtype.Date `json:"expense_date"`
	ExpenseDate_2 pgtype.Date `json:"expense_date_2"`
}

type GetOverviewByCategoryRow struct {
	CategoryID    pgtype.UUID    `json:"category_id"`
	CategoryName  pgtype.Text    `json:"category_name"`
	CategoryColor pgtype.Text    `json:"category_color"`
	CategoryIcon  pgtype.Text    `json:"category_icon"`
	ExpenseCount  int64          `json:"expense_count"`
	TotalAmount   pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) GetOverviewByCategory(ctx context.Context, arg GetOverviewByCategoryParams) ([]GetOverviewByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getOverviewByCategory, arg.GroupID, arg.ExpenseDate, arg.ExpenseDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOverviewByCategoryRow
	for rows.Next() {
		var i GetOverviewByCategoryRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryColor,
			&i.CategoryIcon,
			&i.ExpenseCount,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverviewByMemberOwed = `-- name: GetOverviewByMemberOwed :many
SELECT
    u.id AS user_id,
    u.first_name AS first_name,
    u.last_name AS last_name,
    COALESCE(SUM(es.amount_owed), 0)::decimal(14,2) AS total_owed
FROM expense_splits es
JOIN expenses e ON e.id = es.expense_id
JOIN users u ON u.id = es.user_id
WHERE e.group_id = $1
  AND e.expense_date BETWEEN $2 AND $3
  AND e.is_archived = FALSE
GROUP BY u.id, u.first_name, u.last_name
ORDER BY total_owed DESC
`

type GetOverviewByMemberOwedParams struct {
	GroupID       pgtype.UUID `json:"group_id"`
	ExpenseDate   pgtype.Date `json:"expense_date"`
	ExpenseDate_2 pgtype.Date `json:"expense_date_2"`
}

type GetOverviewByMemberOwedRow struct {
	UserID    pgtype.UUID    `json:"user_id"`
	FirstName string         `json:"first_name"`
	LastName  pgtype.Text    `json:"last_name"`
	TotalOwed pgtype.Numeric `json:"total_owed"`
}

func (q *Queries) GetOverviewByMemberOwed(ctx context.Context, arg GetOverviewByMemberOwedParams) ([]GetOverviewByMemberOwedRow, error) {
	rows, err := q.db.Query(ctx, getOverviewByMemberOwed, arg.GroupID, arg.ExpenseDate, arg.ExpenseDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOverviewByMemberOwedRow
	for rows.Next() {
		var i GetOverviewByMemberOwedRow
		if err := rows.Scan(
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.TotalOwed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverviewByMemberPaid = `-- name: GetOverviewByMemberPaid :many
SELECT
    u.id AS user_id,
    u.first_name AS first_name,
    u.last_name AS last_name,
    COUNT(e.id)::bigint AS expense_count,
    COALESCE(SUM(e.amount), 0)::decimal(14,2) AS total_amount
FROM expenses e
JOIN users u ON u.id = e.paid_by
WHERE e.group_id = $1
  AND e.expense_date BETWEEN $2 AND $3
  AND e.is_archived = FALSE
GROUP BY u.id, u.first_name, u.last_name
ORDER BY total_amount DESC
`

type GetOverviewByMemberPaidParams struct {
	GroupID       pgtype.UUID `json:"group_id"`
	ExpenseDate   pgtype.Date `json:"expense_date"`
	ExpenseDate_2 pgtype.Date `json:"expense_date_2"`
}

type GetOverviewByMemberPaidRow struct {
	UserID       pgtype.UUID    `json:"user_id"`
	FirstName    string         `json:"first_name"`
	LastName     pgtype.Text    `json:"last_name"`
	ExpenseCount int64          `json:"expense_count"`
	TotalAmount  pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) GetOverviewByMemberPaid(ctx context.Context, arg GetOverviewByMemberPaidParams) ([]GetOverviewByMemberPaidRow, error) {
	rows, err := q.db.Query(ctx, getOverviewByMemberPaid, arg.GroupID, arg.ExpenseDate, arg.ExpenseDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOverviewByMemberPaidRow
	for rows.Next() {
		var i GetOverviewByMemberPaidRow
		if err := rows.Scan(
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.ExpenseCount,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverviewDaily = `-- name: GetOverviewDaily :many
SELECT
    expense_date,
    COUNT(*)::bigint AS expense_count,
    COALESCE(SUM(amount), 0)::decimal(14,2) AS total_amount
FROM expenses
WHERE group_id = $1
  AND expense_date BETWEEN $2 AND $3
  AND is_archived = FALSE
GROUP BY expense_date
ORDER BY expense_date ASC
`

type GetOverviewDailyParams struct {
	GroupID       pgtype.UUID `json:"group_id"`
	ExpenseDate   pgtype.Date `json:"expense_date"`
	ExpenseDate_2 pgtype.Date `json:"expense_date_2"`
}

type GetOverviewDailyRow struct {
	ExpenseDate  pgtype.Date    `json:"expense_date"`
	ExpenseCount int64          `json:"expense_count"`
	TotalAmount  pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) GetOverviewDaily(ctx context.Context, arg GetOverviewDailyParams) ([]GetOverviewDailyRow, error) {
	rows, err := q.db.Query(ctx, getOverviewDaily, arg.GroupID, arg.ExpenseDate, arg.ExpenseDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOverviewDailyRow
	for rows.Next() {
		var i GetOverviewDailyRow
		if err := rows.Scan(&i.ExpenseDate, &i.ExpenseCount, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverviewMemberCount = `-- name: GetOverviewMemberCount :one
SELECT COUNT(*)::bigint AS member_count
FROM group_members
WHERE group_id = $1
  AND status = 'active'
`

func (q *Queries) GetOverviewMemberCount(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getOverviewMemberCount, groupID)
	var member_count int64
	err := row.Scan(&member_count)
	return member_count, err
}

const getOverviewRecent = `-- name: GetOverviewRecent :many
SELECT id, group_id, created_by, paid_by, category_id, amount, description, note, split_type, is_archived, archived_at, expense_date, created_at, updated_at, splits_count
FROM expenses
WHERE group_id = $1
  AND expense_date BETWEEN $2 AND $3
  AND is_archived = FALSE
ORDER BY expense_date DESC, created_at DESC
LIMIT 10
`

type GetOverviewRecentParams struct {
	GroupID       pgtype.UUID `json:"group_id"`
	ExpenseDate   pgtype.Date `json:"expense_date"`
	ExpenseDate_2 pgtype.Date `json:"expense_date_2"`
}

func (q *Queries) GetOverviewRecent(ctx context.Context, arg GetOverviewRecentParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, getOverviewRecent, arg.GroupID, arg.ExpenseDate, arg.ExpenseDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreatedBy,
			&i.PaidBy,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.Note,
			&i.SplitType,
			&i.IsArchived,
			&i.ArchivedAt,
			&i.ExpenseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SplitsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverviewSettlementStats = `-- name: GetOverviewSettlementStats :one
SELECT
    COUNT(*)::bigint AS settlement_count,
    COALESCE(SUM(amount), 0)::decimal(14,2) AS settlement_amount
FROM settlements
WHERE group_id = $1
  AND settlement_date BETWEEN $2 AND $3
`

type GetOverviewSettlementStatsParams struct {
	GroupID          pgtype.UUID `json:"group_id"`
	SettlementDate   pgtype.Date `json:"settlement_date"`
	SettlementDate_2 pgtype.Date `json:"settlement_date_2"`
}

type GetOverviewSettlementStatsRow struct {
	SettlementCount  int64          `json:"settlement_count"`
	SettlementAmount pgtype.Numeric `json:"settlement_amount"`
}

func (q *Queries) GetOverviewSettlementStats(ctx context.Context, arg GetOverviewSettlementStatsParams) (GetOverviewSettlementStatsRow, error) {
	row := q.db.QueryRow(ctx, getOverviewSettlementStats, arg.GroupID, arg.SettlementDate, arg.SettlementDate_2)
	var i GetOverviewSettlementStatsRow
	err := row.Scan(&i.SettlementCount, &i.SettlementAmount)
	return i, err
}

const getOverviewStats = `-- name: GetOverviewStats :one
SELECT
    COUNT(*)::bigint AS expense_count,
    COALESCE(SUM(amount), 0)::decimal(14,2) AS total_amount
FROM expenses
WHERE group_id = $1
  AND expense_date BETWEEN $2 AND $3
  AND is_archived = FALSE
`

type GetOverviewStatsParams struct {
	GroupID       pgtype.UUID `json:"group_id"`
	ExpenseDate   pgtype.Date `json:"expense_date"`
	ExpenseDate_2 pgtype.Date `json:"expense_date_2"`
}

type GetOverviewStatsRow struct {
	ExpenseCount int64          `json:"expense_count"`
	TotalAmount  pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) GetOverviewStats(ctx context.Context, arg GetOverviewStatsParams) (GetOverviewStatsRow, error) {
	row := q.db.QueryRow(ctx, getOverviewStats, arg.GroupID, arg.ExpenseDate, arg.ExpenseDate_2)
	var i GetOverviewStatsRow
	err := row.Scan(&i.ExpenseCount, &i.TotalAmount)
	return i, err
}
