// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personal_budgets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPersonalBudget = `-- name: CreatePersonalBudget :one
INSERT INTO personal_budgets (
    user_id,
    amount_limit,
    period,
    start_date,
    end_date,
    alert_threshold
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, user_id, amount_limit, period, start_date, end_date, alert_threshold, created_at, updated_at
`

type CreatePersonalBudgetParams struct {
	UserID         pgtype.UUID    `json:"user_id"`
	AmountLimit    pgtype.Numeric `json:"amount_limit"`
	Period         BudgetPeriod   `json:"period"`
	StartDate      pgtype.Date    `json:"start_date"`
	EndDate        pgtype.Date    `json:"end_date"`
	AlertThreshold int32          `json:"alert_threshold"`
}

func (q *Queries) CreatePersonalBudget(ctx context.Context, arg CreatePersonalBudgetParams) (PersonalBudget, error) {
	row := q.db.QueryRow(ctx, createPersonalBudget,
		arg.UserID,
		arg.AmountLimit,
		arg.Period,
		arg.StartDate,
		arg.EndDate,
		arg.AlertThreshold,
	)
	var i PersonalBudget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountLimit,
		&i.Period,
		&i.StartDate,
		&i.EndDate,
		&i.AlertThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePersonalBudget = `-- name: DeletePersonalBudget :exec
DELETE FROM personal_budgets WHERE id = $1
`

func (q *Queries) DeletePersonalBudget(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePersonalBudget, id)
	return err
}

const getPersonalBudgetByID = `-- name: GetPersonalBudgetByID :one
SELECT id, user_id, amount_limit, period, start_date, end_date, alert_threshold, created_at, updated_at FROM personal_budgets WHERE id = $1
`

func (q *Queries) GetPersonalBudgetByID(ctx context.Context, id pgtype.UUID) (PersonalBudget, error) {
	row := q.db.QueryRow(ctx, getPersonalBudgetByID, id)
	var i PersonalBudget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountLimit,
		&i.Period,
		&i.StartDate,
		&i.EndDate,
		&i.AlertThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPersonalBudgetsByUserID = `-- name: ListPersonalBudgetsByUserID :many
SELECT id, user_id, amount_limit, period, start_date, end_date, alert_threshold, created_at, updated_at FROM personal_budgets WHERE user_id = $1 ORDER BY start_date DESC
LIMIT $3 OFFSET $2
`

type ListPersonalBudgetsByUserIDParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

func (q *Queries) ListPersonalBudgetsByUserID(ctx context.Context, arg ListPersonalBudgetsByUserIDParams) ([]PersonalBudget, error) {
	rows, err := q.db.Query(ctx, listPersonalBudgetsByUserID, arg.UserID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersonalBudget
	for rows.Next() {
		var i PersonalBudget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AmountLimit,
			&i.Period,
			&i.StartDate,
			&i.EndDate,
			&i.AlertThreshold,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePersonalBudget = `-- name: UpdatePersonalBudget :one
UPDATE personal_budgets SET
    amount_limit = COALESCE($1, amount_limit),
    period = COALESCE($2, period),
    start_date = COALESCE($3, start_date),
    end_date = COALESCE($4, end_date),
    alert_threshold = COALESCE($5, alert_threshold)
WHERE id = $6
RETURNING id, user_id, amount_limit, period, start_date, end_date, alert_threshold, created_at, updated_at
`

type UpdatePersonalBudgetParams struct {
	AmountLimit    pgtype.Numeric   `json:"amount_limit"`
	Period         NullBudgetPeriod `json:"period"`
	StartDate      pgtype.Date      `json:"start_date"`
	EndDate        pgtype.Date      `json:"end_date"`
	AlertThreshold pgtype.Int4      `json:"alert_threshold"`
	ID             pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdatePersonalBudget(ctx context.Context, arg UpdatePersonalBudgetParams) (PersonalBudget, error) {
	row := q.db.QueryRow(ctx, updatePersonalBudget,
		arg.AmountLimit,
		arg.Period,
		arg.StartDate,
		arg.EndDate,
		arg.AlertThreshold,
		arg.ID,
	)
	var i PersonalBudget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountLimit,
		&i.Period,
		&i.StartDate,
		&i.EndDate,
		&i.AlertThreshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
