// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settlements.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSettlement = `-- name: CreateSettlement :one
INSERT INTO settlements (
    group_id,
    from_user_id,
    to_user_id,
    amount,
    payment_method,
    note,
    settlement_date
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, group_id, from_user_id, to_user_id, amount, payment_method, note, settlement_date, created_at, updated_at
`

type CreateSettlementParams struct {
	GroupID        pgtype.UUID    `json:"group_id"`
	FromUserID     pgtype.UUID    `json:"from_user_id"`
	ToUserID       pgtype.UUID    `json:"to_user_id"`
	Amount         pgtype.Numeric `json:"amount"`
	PaymentMethod  PaymentMethod  `json:"payment_method"`
	Note           pgtype.Text    `json:"note"`
	SettlementDate pgtype.Date    `json:"settlement_date"`
}

func (q *Queries) CreateSettlement(ctx context.Context, arg CreateSettlementParams) (Settlement, error) {
	row := q.db.QueryRow(ctx, createSettlement,
		arg.GroupID,
		arg.FromUserID,
		arg.ToUserID,
		arg.Amount,
		arg.PaymentMethod,
		arg.Note,
		arg.SettlementDate,
	)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Amount,
		&i.PaymentMethod,
		&i.Note,
		&i.SettlementDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSettlement = `-- name: DeleteSettlement :exec
DELETE FROM settlements WHERE id = $1
`

func (q *Queries) DeleteSettlement(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSettlement, id)
	return err
}

const getSettlementByID = `-- name: GetSettlementByID :one
SELECT id, group_id, from_user_id, to_user_id, amount, payment_method, note, settlement_date, created_at, updated_at FROM settlements WHERE id = $1
`

func (q *Queries) GetSettlementByID(ctx context.Context, id pgtype.UUID) (Settlement, error) {
	row := q.db.QueryRow(ctx, getSettlementByID, id)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Amount,
		&i.PaymentMethod,
		&i.Note,
		&i.SettlementDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSettlementsByGroupAndUser = `-- name: ListSettlementsByGroupAndUser :many
SELECT id, group_id, from_user_id, to_user_id, amount, payment_method, note, settlement_date, created_at, updated_at FROM settlements
WHERE group_id = $1 AND (from_user_id = $2 OR to_user_id = $2)
ORDER BY settlement_date DESC, created_at DESC
`

type ListSettlementsByGroupAndUserParams struct {
	GroupID    pgtype.UUID `json:"group_id"`
	FromUserID pgtype.UUID `json:"from_user_id"`
}

func (q *Queries) ListSettlementsByGroupAndUser(ctx context.Context, arg ListSettlementsByGroupAndUserParams) ([]Settlement, error) {
	rows, err := q.db.Query(ctx, listSettlementsByGroupAndUser, arg.GroupID, arg.FromUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Settlement
	for rows.Next() {
		var i Settlement
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.FromUserID,
			&i.ToUserID,
			&i.Amount,
			&i.PaymentMethod,
			&i.Note,
			&i.SettlementDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlementsByGroupID = `-- name: ListSettlementsByGroupID :many
SELECT id, group_id, from_user_id, to_user_id, amount, payment_method, note, settlement_date, created_at, updated_at FROM settlements
WHERE group_id = $1
ORDER BY settlement_date DESC, created_at DESC
`

func (q *Queries) ListSettlementsByGroupID(ctx context.Context, groupID pgtype.UUID) ([]Settlement, error) {
	rows, err := q.db.Query(ctx, listSettlementsByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Settlement
	for rows.Next() {
		var i Settlement
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.FromUserID,
			&i.ToUserID,
			&i.Amount,
			&i.PaymentMethod,
			&i.Note,
			&i.SettlementDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSettlement = `-- name: UpdateSettlement :one
UPDATE settlements SET
    amount = COALESCE($1, amount),
    payment_method = COALESCE($2, payment_method),
    note = COALESCE($3, note),
    settlement_date = COALESCE($4, settlement_date)
WHERE id = $5
RETURNING id, group_id, from_user_id, to_user_id, amount, payment_method, note, settlement_date, created_at, updated_at
`

type UpdateSettlementParams struct {
	Amount         pgtype.Numeric    `json:"amount"`
	PaymentMethod  NullPaymentMethod `json:"payment_method"`
	Note           pgtype.Text       `json:"note"`
	SettlementDate pgtype.Date       `json:"settlement_date"`
	ID             pgtype.UUID       `json:"id"`
}

func (q *Queries) UpdateSettlement(ctx context.Context, arg UpdateSettlementParams) (Settlement, error) {
	row := q.db.QueryRow(ctx, updateSettlement,
		arg.Amount,
		arg.PaymentMethod,
		arg.Note,
		arg.SettlementDate,
		arg.ID,
	)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Amount,
		&i.PaymentMethod,
		&i.Note,
		&i.SettlementDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
