// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settlement_splits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSettlementSplit = `-- name: CreateSettlementSplit :one
INSERT INTO settlement_splits (
    settlement_id,
    expense_split_id
) VALUES (
    $1,
    $2
)
RETURNING id, settlement_id, expense_split_id, created_at
`

type CreateSettlementSplitParams struct {
	SettlementID   pgtype.UUID `json:"settlement_id"`
	ExpenseSplitID pgtype.UUID `json:"expense_split_id"`
}

func (q *Queries) CreateSettlementSplit(ctx context.Context, arg CreateSettlementSplitParams) (SettlementSplit, error) {
	row := q.db.QueryRow(ctx, createSettlementSplit, arg.SettlementID, arg.ExpenseSplitID)
	var i SettlementSplit
	err := row.Scan(
		&i.ID,
		&i.SettlementID,
		&i.ExpenseSplitID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSettlementSplit = `-- name: DeleteSettlementSplit :exec
DELETE FROM settlement_splits WHERE id = $1
`

func (q *Queries) DeleteSettlementSplit(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSettlementSplit, id)
	return err
}

const deleteSettlementSplitsBySettlementID = `-- name: DeleteSettlementSplitsBySettlementID :exec
DELETE FROM settlement_splits WHERE settlement_id = $1
`

func (q *Queries) DeleteSettlementSplitsBySettlementID(ctx context.Context, settlementID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSettlementSplitsBySettlementID, settlementID)
	return err
}

const getSettlementSplitByID = `-- name: GetSettlementSplitByID :one
SELECT id, settlement_id, expense_split_id, created_at FROM settlement_splits WHERE id = $1
`

func (q *Queries) GetSettlementSplitByID(ctx context.Context, id pgtype.UUID) (SettlementSplit, error) {
	row := q.db.QueryRow(ctx, getSettlementSplitByID, id)
	var i SettlementSplit
	err := row.Scan(
		&i.ID,
		&i.SettlementID,
		&i.ExpenseSplitID,
		&i.CreatedAt,
	)
	return i, err
}

const listSettlementSplitsByExpenseSplitID = `-- name: ListSettlementSplitsByExpenseSplitID :many
SELECT id, settlement_id, expense_split_id, created_at FROM settlement_splits WHERE expense_split_id = $1 ORDER BY created_at ASC
LIMIT $3 OFFSET $2
`

type ListSettlementSplitsByExpenseSplitIDParams struct {
	ExpenseSplitID pgtype.UUID `json:"expense_split_id"`
	PageOffset     int32       `json:"page_offset"`
	PageLimit      int32       `json:"page_limit"`
}

func (q *Queries) ListSettlementSplitsByExpenseSplitID(ctx context.Context, arg ListSettlementSplitsByExpenseSplitIDParams) ([]SettlementSplit, error) {
	rows, err := q.db.Query(ctx, listSettlementSplitsByExpenseSplitID, arg.ExpenseSplitID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SettlementSplit
	for rows.Next() {
		var i SettlementSplit
		if err := rows.Scan(
			&i.ID,
			&i.SettlementID,
			&i.ExpenseSplitID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlementSplitsBySettlementID = `-- name: ListSettlementSplitsBySettlementID :many
SELECT id, settlement_id, expense_split_id, created_at FROM settlement_splits WHERE settlement_id = $1 ORDER BY created_at ASC
LIMIT $3 OFFSET $2
`

type ListSettlementSplitsBySettlementIDParams struct {
	SettlementID pgtype.UUID `json:"settlement_id"`
	PageOffset   int32       `json:"page_offset"`
	PageLimit    int32       `json:"page_limit"`
}

func (q *Queries) ListSettlementSplitsBySettlementID(ctx context.Context, arg ListSettlementSplitsBySettlementIDParams) ([]SettlementSplit, error) {
	rows, err := q.db.Query(ctx, listSettlementSplitsBySettlementID, arg.SettlementID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SettlementSplit
	for rows.Next() {
		var i SettlementSplit
		if err := rows.Scan(
			&i.ID,
			&i.SettlementID,
			&i.ExpenseSplitID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
