// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    first_name,
    last_name,
    avatar_url,
    timezone,
    email_verified_at,
    last_login_mode,
    last_login_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, email, first_name, last_name, avatar_url, is_active, timezone, email_verified_at, last_login_mode, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	Email           string
	FirstName       string
	LastName        pgtype.Text
	AvatarUrl       pgtype.Text
	Timezone        string
	EmailVerifiedAt pgtype.Timestamptz
	LastLoginMode   NullLoginProvider
	LastLoginAt     pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
		arg.Timezone,
		arg.EmailVerifiedAt,
		arg.LastLoginMode,
		arg.LastLoginAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.Timezone,
		&i.EmailVerifiedAt,
		&i.LastLoginMode,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWithEmail = `-- name: GetUserWithEmail :one
SELECT id, email, first_name, last_name, avatar_url, is_active, timezone, email_verified_at, last_login_mode, last_login_at, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserWithEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserWithEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.Timezone,
		&i.EmailVerifiedAt,
		&i.LastLoginMode,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
